export interface Question {
  id: string;
  question: string;
  topic: string;
  answer?: string; // The "correct" answer for the AI to reference
}

const allQuestions: Record<string, Question[]> = {
  // Grade 10 Mathematics
  "Algebraic expressions": [
    { id: 'alg-exp-1', topic: 'Algebraic expressions', question: 'Simplify the following expression: (2x + 3y) - (x - 2y)' },
    { id: 'alg-exp-2', topic: 'Algebraic expressions', question: 'Expand and simplify: (x - 5)(x + 3)' },
    { id: 'alg-exp-3', topic: 'Algebraic expressions', question: 'Factorise the following expression completely: 2x² - 8' },
    { id: 'alg-exp-4', topic: 'Algebraic expressions', question: 'Simplify: (3a²b³) / (9a⁴b)' },
    { id: 'alg-exp-5', topic: 'Algebraic expressions', question: 'If x = -2, what is the value of 3x² - 5x + 2?' },
    { id: 'alg-exp-6', topic: 'Algebraic expressions', question: 'Factorise the trinomial: x² - 7x + 12' },
    { id: 'alg-exp-7', topic: 'Algebraic expressions', question: 'Expand: (2a - b)²' },
    { id: 'alg-exp-8', topic: 'Algebraic expressions', question: 'Simplify the fraction: (x² - 9) / (x + 3)' },
    { id: 'alg-exp-9', topic: 'Algebraic expressions', question: 'Find the product of (y - 4) and (y + 4)' },
    { id: 'alg-exp-10', topic: 'Algebraic expressions', question: 'Factorise by grouping: xy + 2x + 3y + 6' },
    { id: 'alg-exp-11', topic: 'Algebraic expressions', question: 'Simplify: 5x - [3x - (2y - x)]' },
    { id: 'alg-exp-12', topic: 'Algebraic expressions', question: 'Expand and simplify: (3x + 1)(2x - 5)' },
    { id: 'alg-exp-13', topic: 'Algebraic expressions', question: 'Factorise: 27x³ - 8y³' },
    { id: 'alg-exp-14', topic: 'Algebraic expressions', question: 'Simplify: √(16x¹⁶)' },
    { id: 'alg-exp-15', topic: 'Algebraic expressions', question: 'What is the highest common factor of 12a³b² and 18a²b⁴?' },
    { id: 'alg-exp-16', topic: 'Algebraic expressions', question: 'Factorise: p² - 10p + 25' },
    { id: 'alg-exp-17', topic: 'Algebraic expressions', question: 'Simplify: (4x² / 2x) * 3x' },
    { id: 'alg-exp-18', topic: 'Algebraic expressions', question: 'Expand: (a + b + c)²' },
    { id: 'alg-exp-19', topic: 'Algebraic expressions', question: 'Factorise: 5x²y - 10xy²' },
    { id: 'alg-exp-20', topic: 'Algebraic expressions', question: 'Simplify: (x² - y²) / (x - y)' },
    { id: 'alg-exp-21', topic: 'Algebraic expressions', question: 'If a+b=7 and ab=12, find the value of a²+b².' },
    { id: 'alg-exp-22', topic: 'Algebraic expressions', question: 'Factorise the expression: x(a-c) + y(c-a)' },
    { id: 'alg-exp-23', topic: 'Algebraic expressions', question: 'Expand and simplify: (x + 1/x)²' },
    { id: 'alg-exp-24', topic: 'Algebraic expressions', question: 'Simplify the algebraic fraction: (a² - 4) / (a² + 2a)' },
    { id: 'alg-exp-25', topic: 'Algebraic expressions', question: 'Subtract 5a² - 2a + 1 from 8a² + 3a - 6' },
  ],
  "Trigonometry": [
    { id: 'trig-1', topic: 'Trigonometry', question: 'In a right-angled triangle, if the side opposite to angle θ is 3 and the adjacent side is 4, what is the value of tan(θ)?' },
    { id: 'trig-2', topic: 'Trigonometry', question: 'What is the value of sin(30°)?' },
    { id: 'trig-3', topic: 'Trigonometry', question: 'If cos(A) = 0.8 and A is an acute angle, find the value of sin(A).' },
    { id: 'trig-4', topic: 'Trigonometry', question: 'Solve for x if 2sin(x) = 1, for 0° < x < 90°.' },
    { id: 'trig-5', topic: 'Trigonometry', question: 'A ladder 10m long leans against a vertical wall, making an angle of 60° with the ground. How high up the wall does the ladder reach?' },
    { id: 'trig-6', topic: 'Trigonometry', question: 'Simplify the expression: sin²(θ) + cos²(θ).' },
    { id: 'trig-7', topic: 'Trigonometry', question: 'What is the reciprocal of the sine function called?' },
    { id: 'trig-8', topic: 'Trigonometry', question: 'In a right-angled triangle, the hypotenuse is 13 units and one of the other sides is 5 units. Find the length of the third side.' },
    { id: 'trig-9', topic: 'Trigonometry', question: 'Find the value of tan(45°).' },
    { id: 'trig-10', topic: 'Trigonometry', question: 'If tan(θ) = 1, what is the value of θ for 0° < θ < 90°?' },
    { id: 'trig-11', topic: 'Trigonometry', question: 'Simplify: sin(A) / cos(A).' },
    { id: 'trig-12', topic: 'Trigonometry', question: 'From a point 20m away from the foot of a tower, the angle of elevation to the top of the tower is 30°. Find the height of the tower.' },
    { id: 'trig-13', topic: 'Trigonometry', question: 'What is the value of cos(90°)?' },
    { id: 'trig-14', topic: 'Trigonometry', question: 'If sin(x) = cos(x) for an acute angle x, what is the value of x?' },
    { id: 'trig-15', topic: 'Trigonometry', question: 'Which quadrant does the angle 150° lie in?' },
    { id: 'trig-16', topic: 'Trigonometry', question: 'If cot(B) = 3/4, find tan(B).' },
    { id: 'trig-17', topic: 'Trigonometry', question: 'What is the fundamental identity of trigonometry?' },
    { id: 'trig-18', topic: 'Trigonometry', question: 'Solve for θ: tan(θ) = √3, where 0° < θ < 90°.' },
    { id: 'trig-19', topic: 'Trigonometry', question: 'The angle of depression from the top of a cliff to a boat at sea is 45°. If the cliff is 50m high, how far is the boat from the base of the cliff?' },
    { id: 'trig-20', topic: 'Trigonometry', question: 'What is the value of 1 - sin²(A)?' },
    { id: 'trig-21', topic: 'Trigonometry', question: 'Which trigonometric function is positive in the 3rd quadrant?' },
    { id: 'trig-22', topic: 'Trigonometry', question: 'Express sin(250°) in terms of a reference angle.' },
    { id: 'trig-23', topic: 'Trigonometry', question: 'If a triangle has sides 3, 4, and 5, is it a right-angled triangle? Why?' },
    { id: 'trig-24', topic: 'Trigonometry', question: 'Simplify: tan(180° + x).' },
    { id: 'trig-25', topic: 'Trigonometry', question: 'What is the period of the graph y = sin(x)?' },
  ],
  "Functions": [
    { id: 'func-1', topic: 'Functions', question: 'Given f(x) = 2x - 3, find f(5).' },
    { id: 'func-2', topic: 'Functions', question: 'Is the relation {(1, 2), (2, 4), (3, 6), (1, 5)} a function? Why or why not?' },
    { id: 'func-3', topic: 'Functions', question: 'What is the domain of the function f(x) = √(x - 2)?' },
    { id: 'func-4', topic: 'Functions', question: 'For the parabola y = x² - 4, what is the y-intercept?' },
    { id: 'func-5', topic: 'Functions', question: 'Find the equation of the straight line passing through points (1, 2) and (3, 8).' },
    { id: 'func-6', topic: 'Functions', question: 'What is the range of the function f(x) = |x|?' },
    { id: 'func-7', topic: 'Functions', question: 'Given g(x) = x² + 1, find g(x-1).' },
    { id: 'func-8', topic: 'Functions', question: 'What is the turning point (vertex) of the parabola y = (x - 3)² + 5?' },
    { id: 'func-9', topic: 'Functions', question: 'Is the graph of x² + y² = 9 a function?' },
    { id: 'func-10', topic: 'Functions', question: 'Find the inverse of the function f(x) = 3x + 2.' },
    { id: 'func-11', topic: 'Functions', question: 'What are the x-intercepts of the function y = x² - 5x + 6?' },
    { id: 'func-12', topic: 'Functions', question: 'Describe the transformation that maps the graph of y = x² to y = x² - 5.' },
    { id: 'func-13', topic: 'Functions', question: 'If f(x) = 2x and g(x) = x + 1, find f(g(3)).' },
    { id: 'func-14', topic: 'Functions', question: 'What is the axis of symmetry for the parabola y = 2(x + 1)² - 3?' },
    { id: 'func-15', topic: 'Functions', question: 'Find the domain of f(x) = 1 / (x - 4).' },
    { id: 'func-16', topic: 'Functions', question: 'For the hyperbola y = 2/x + 1, what is the horizontal asymptote?' },
    { id: 'func-17', topic: 'Functions', question: 'Given f(x) = x³, find f(-2).' },
    { id: 'func-18', topic: 'Functions', question: 'What does the vertical line test determine?' },
    { id: 'func-19', topic: 'Functions', question: 'Find the gradient of the line perpendicular to y = -2x + 5.' },
    { id: 'func-20', topic: 'Functions', question: 'What is the range of f(x) = -x²?' },
    { id: 'func-21', topic: 'Functions', question: 'Sketch the graph of y = 2^x. What is this type of function called?' },
    { id: 'func-22', topic: 'Functions', question: 'If a function is one-to-one, what does that mean about its inverse?' },
    { id: 'func-23', topic: 'Functions', question: 'What is the asymptote of the exponential function y = 3^(x-1) + 2?' },
    { id: 'func-24', topic: 'Functions', question: 'Determine if the function f(x) = x² is even, odd, or neither.' },
    { id: 'func-25', topic: 'Functions', question: 'Find the point of intersection of the lines y = x + 1 and y = -x + 3.' },
  ],
  // Grade 12 Calculus
  "Calculus (Differential)": [
    { id: 'calc-1', topic: 'Calculus (Differential)', question: 'Find the derivative of f(x) = x³ - 4x² + 7x - 1 from first principles.' },
    { id: 'calc-2', topic: 'Calculus (Differential)', question: 'Determine dy/dx if y = 5x⁴ - 3x⁻².' },
    { id: 'calc-3', topic: 'Calculus (Differential)', question: 'Find the derivative of f(x) = (2x + 1)(x - 3).' },
    { id: 'calc-4', topic: 'Calculus (Differential)', question: 'Find the equation of the tangent to the curve f(x) = x² - 3x at the point where x = 4.' },
    { id: 'calc-5', topic: 'Calculus (Differential)', question: 'Determine the coordinates of the turning points of the function f(x) = x³ - 3x² - 9x + 5.' },
    { id: 'calc-6', topic: 'Calculus (Differential)', question: 'Find f\'(x) if f(x) = √x + 1/x.' },
    { id: 'calc-7', topic: 'Calculus (Differential)', question: 'For which values of x is the function f(x) = 2x³ - 3x² - 12x increasing?' },
    { id: 'calc-8', topic: 'Calculus (Differential)', question: 'Find the second derivative, f\'\'(x), of the function f(x) = x³ + 6x² - 1.' },
    { id: 'calc-9', topic: 'Calculus (Differential)', question: 'Determine the point of inflection for the graph of f(x) = x³ - 6x² + 5x + 1.' },
    { id: 'calc-10', topic: 'Calculus (Differential)', question: 'A company\'s profit is given by P(x) = -x³ + 9x² + 120x - 400, where x is the number of units sold. Find the number of units that must be sold to maximize the profit.' },
    { id: 'calc-11', topic: 'Calculus (Differential)', question: 'Find the average gradient of f(x) = x² between x = 1 and x = 3.' },
    { id: 'calc-12', topic: 'Calculus (Differential)', question: 'Differentiate g(x) = (4x³ - 2x) / x with respect to x.' },
    { id: 'calc-13', topic: 'Calculus (Differential)', question: 'Find the equation of the normal to the curve y = 2x² - 1 at the point (2, 7).' },
    { id: 'calc-14', topic: 'Calculus (Differential)', question: 'Determine the concavity of the function f(x) = -x³ + 3x² - 2 at x = 2.' },
    { id: 'calc-15', topic: 'Calculus (Differential)', question: 'Find the derivative of y = (2 - 5x)³ using the chain rule.' },
    { id: 'calc-16', topic: 'Calculus (Differential)', question: 'The displacement of a particle is given by s(t) = t³ - 6t² + 9t. Find the velocity of the particle when its acceleration is zero.' },
    { id: 'calc-17', topic: 'Calculus (Differential)', question: 'What is the limit of (x² - 4) / (x - 2) as x approaches 2?' },
    { id: 'calc-18', topic: 'Calculus (Differential)', question: 'Use differentiation to find the minimum value of the function f(x) = x² + 4x + 5.' },
    { id: 'calc-19', topic: 'Calculus (Differential)', question: 'Differentiate with respect to x: y = 3 / x⁴.' },
    { id: 'calc-20', topic: 'Calculus (Differential)', question: 'A rectangular box has a square base and its volume is 108 cm³. Find the dimensions of the box that will minimize its surface area.' },
    { id: 'calc-21', topic: 'Calculus (Differential)', question: 'Interpret f\'(a) = 0 in the context of the graph of f(x).' },
    { id: 'calc-22', topic: 'Calculus (Differential)', question: 'Find the derivative of f(x) = (x³ + 27) / (x + 3).' },
    { id: 'calc-23', topic: 'Calculus (Differential)', question: 'If the gradient of the tangent to f(x) = ax² + bx at x = 1 is 5, and f(1) = 3, find the values of a and b.' },
    { id: 'calc-24', topic: 'Calculus (Differential)', question: 'When is a function not differentiable at a point?' },
    { id: 'calc-25', topic: 'Calculus (Differential)', question: 'The volume of a sphere is increasing at a rate of 3 cm³/s. Find the rate of increase of the radius when the radius is 2 cm.' },
  ],
  // Add other topics and questions here...
};

export const getQuestionsForTopic = (topic: string, grade: number): Question[] => {
  // This is a simple lookup. In a real app, this could be more complex,
  // potentially filtering by grade as well if questions were tagged by grade.
  // For now, we'll just use the topic name as the key.
  return allQuestions[topic] || [];
};
