version: "3.9"

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

x-appwrite-image: &appwrite-image appwrite/appwrite:${APPWRITE_VERSION:-1.6.1}

services:
  web:
    container_name: caps-tutor-web
    build:
      context: .
      target: runner
    env_file:
      - .env.local
      - .env.docker
    environment:
      PORT: ${PORT:-3000}
      HOSTNAME: ${HOSTNAME:-0.0.0.0}
    cpus: ${WEB_CPUS:-2}
    mem_limit: ${WEB_MEM_LIMIT:-4g}
    ports:
      - "${WEB_PORT:-9002}:3000"
    depends_on:
      - appwrite
    restart: unless-stopped
    networks:
      - gateway
      - appwrite
    logging: *default-logging

  traefik:
    container_name: appwrite-traefik
    image: traefik:2.11
    restart: unless-stopped
    command:
      - --log.level=INFO
      - --api.insecure=true
      - --providers.file.directory=/storage/config
      - --providers.file.watch=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - '--providers.docker.constraints=Label(`traefik.constraint-label-stack`,`appwrite`)'
      - --entrypoints.appwrite_web.address=:80
      - --entrypoints.appwrite_websecure.address=:443
      - --accesslog=true
    ports:
      - "${TRAEFIK_HTTP_PORT:-9500}:80"
      - "${TRAEFIK_HTTPS_PORT:-9443}:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-config:/storage/config:ro
      - appwrite-certificates:/storage/certificates:ro
    depends_on:
      - appwrite
      - appwrite-console
      - appwrite-realtime
    networks:
      - gateway
      - appwrite
      - runtimes
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=appwrite
      - traefik.docker.network=appwrite
    logging: *default-logging

  appwrite:
    container_name: appwrite
    image: *appwrite-image
    restart: unless-stopped
    env_file:
      - .env.appwrite
    environment:
      _APP_DOMAIN: ${_APP_DOMAIN:-localhost}
      _APP_DOMAIN_TARGET: ${_APP_DOMAIN_TARGET:-localhost}
      _APP_DOMAIN_FUNCTIONS: ${_APP_DOMAIN_FUNCTIONS:-localhost}
      _APP_CONSOLE_DOMAIN: ${_APP_CONSOLE_DOMAIN:-localhost}
      _APP_DB_HOST: mariadb
      _APP_DB_PORT: 3306
      _APP_REDIS_HOST: redis
      _APP_REDIS_PORT: 6379
      _APP_STORAGE_DEVICE: ${_APP_STORAGE_DEVICE:-local}
      _APP_EXECUTOR_HOST: http://openruntimes-executor/v1
    cpus: ${APPWRITE_CPUS:-2}
    mem_limit: ${APPWRITE_MEM_LIMIT:-4g}
    entrypoint:
      - php
      - -e
      - app/http.php
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw
    depends_on:
      - mariadb
      - redis
      - maildev
    networks:
      - appwrite
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=appwrite
      - traefik.docker.network=appwrite
      - traefik.http.services.appwrite_api.loadbalancer.server.port=80
      - traefik.http.routers.appwrite_api_http.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_api_http.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite_api_http.service=appwrite_api
      - traefik.http.routers.appwrite_api_https.entrypoints=appwrite_websecure
      - traefik.http.routers.appwrite_api_https.rule=PathPrefix(`/`)
      - traefik.http.routers.appwrite_api_https.service=appwrite_api
      - traefik.http.routers.appwrite_api_https.tls=true
    ports:
      - "${APPWRITE_HTTP_PORT:-9501}:80"
    logging: *default-logging

  appwrite-console:
    container_name: appwrite-console
    image: appwrite/console:5.2.58
    restart: unless-stopped
    env_file:
      - .env.appwrite
    networks:
      - appwrite
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=appwrite
      - traefik.docker.network=appwrite
      - traefik.http.services.appwrite_console.loadbalancer.server.port=80
      - traefik.http.routers.appwrite_console_http.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_console_http.rule=PathPrefix(`/console`)
      - traefik.http.routers.appwrite_console_http.service=appwrite_console
      - traefik.http.routers.appwrite_console_https.entrypoints=appwrite_websecure
      - traefik.http.routers.appwrite_console_https.rule=PathPrefix(`/console`)
      - traefik.http.routers.appwrite_console_https.service=appwrite_console
      - traefik.http.routers.appwrite_console_https.tls=true
    ports:
      - "${APPWRITE_CONSOLE_PORT:-9502}:80"
    logging: *default-logging

  appwrite-realtime:
    container_name: appwrite-realtime
    image: *appwrite-image
    entrypoint:
      - realtime
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - mariadb
      - redis
    networks:
      - appwrite
    labels:
      - traefik.enable=true
      - traefik.constraint-label-stack=appwrite
      - traefik.docker.network=appwrite
      - traefik.http.services.appwrite_realtime.loadbalancer.server.port=80
      - traefik.http.routers.appwrite_realtime_ws.entrypoints=appwrite_web
      - traefik.http.routers.appwrite_realtime_ws.rule=PathPrefix(`/v1/realtime`)
      - traefik.http.routers.appwrite_realtime_ws.service=appwrite_realtime
      - traefik.http.routers.appwrite_realtime_wss.entrypoints=appwrite_websecure
      - traefik.http.routers.appwrite_realtime_wss.rule=PathPrefix(`/v1/realtime`)
      - traefik.http.routers.appwrite_realtime_wss.service=appwrite_realtime
      - traefik.http.routers.appwrite_realtime_wss.tls=true
    ports:
      - "${APPWRITE_REALTIME_PORT:-9505}:80"
    logging: *default-logging

  appwrite-worker-audits:
    container_name: appwrite-worker-audits
    image: *appwrite-image
    entrypoint:
      - worker-audits
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - redis
      - mariadb
    networks:
      - appwrite
    logging: *default-logging

  appwrite-worker-webhooks:
    container_name: appwrite-worker-webhooks
    image: *appwrite-image
    entrypoint:
      - worker-webhooks
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - redis
      - mariadb
      - maildev
    networks:
      - appwrite
    logging: *default-logging

  appwrite-worker-deletes:
    container_name: appwrite-worker-deletes
    image: *appwrite-image
    entrypoint:
      - worker-deletes
    restart: unless-stopped
    env_file:
      - .env.appwrite
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-certificates:/storage/certificates:rw
    depends_on:
      - redis
      - mariadb
    networks:
      - appwrite
    logging: *default-logging

  appwrite-worker-databases:
    container_name: appwrite-worker-databases
    image: *appwrite-image
    entrypoint:
      - worker-databases
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - redis
      - mariadb
    networks:
      - appwrite
    logging: *default-logging

  appwrite-worker-builds:
    container_name: appwrite-worker-builds
    image: *appwrite-image
    entrypoint:
      - worker-builds
    restart: unless-stopped
    env_file:
      - .env.appwrite
    volumes:
      - appwrite-functions:/storage/functions:rw
      - appwrite-builds:/storage/builds:rw
    depends_on:
      - redis
      - mariadb
    networks:
      - appwrite
    logging: *default-logging

  appwrite-worker-certificates:
    container_name: appwrite-worker-certificates
    image: *appwrite-image
    entrypoint:
      - worker-certificates
    restart: unless-stopped
    env_file:
      - .env.appwrite
    volumes:
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
    depends_on:
      - redis
      - mariadb
    networks:
      - appwrite
    logging: *default-logging

  appwrite-worker-functions:
    container_name: appwrite-worker-functions
    image: *appwrite-image
    entrypoint:
      - worker-functions
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - redis
      - mariadb
      - openruntimes-executor
    networks:
      - appwrite
    logging: *default-logging

  appwrite-worker-mails:
    container_name: appwrite-worker-mails
    image: *appwrite-image
    entrypoint:
      - worker-mails
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - redis
      - maildev
    networks:
      - appwrite
    logging: *default-logging

  appwrite-worker-messaging:
    container_name: appwrite-worker-messaging
    image: *appwrite-image
    entrypoint:
      - worker-messaging
    restart: unless-stopped
    env_file:
      - .env.appwrite
    volumes:
      - appwrite-uploads:/storage/uploads:rw
    depends_on:
      - redis
    networks:
      - appwrite
    logging: *default-logging

  appwrite-worker-migrations:
    container_name: appwrite-worker-migrations
    image: *appwrite-image
    entrypoint:
      - worker-migrations
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - mariadb
    networks:
      - appwrite
    logging: *default-logging

  appwrite-task-maintenance:
    container_name: appwrite-task-maintenance
    image: *appwrite-image
    entrypoint:
      - maintenance
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - redis
    networks:
      - appwrite
    logging: *default-logging

  appwrite-task-scheduler-functions:
    container_name: appwrite-task-scheduler-functions
    image: *appwrite-image
    entrypoint:
      - schedule-functions
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - mariadb
      - redis
    networks:
      - appwrite
    logging: *default-logging

  appwrite-task-scheduler-executions:
    container_name: appwrite-task-scheduler-executions
    image: *appwrite-image
    entrypoint:
      - schedule-executions
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - mariadb
      - redis
    networks:
      - appwrite
    logging: *default-logging

  appwrite-task-scheduler-messages:
    container_name: appwrite-task-scheduler-messages
    image: *appwrite-image
    entrypoint:
      - schedule-messages
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - mariadb
      - redis
    networks:
      - appwrite
    logging: *default-logging

  appwrite-worker-usage:
    container_name: appwrite-worker-usage
    image: *appwrite-image
    entrypoint:
      - worker-usage
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - redis
      - mariadb
    networks:
      - appwrite
    logging: *default-logging

  openruntimes-executor:
    container_name: openruntimes-executor
    hostname: exc1
    image: openruntimes/executor:0.6.11
    restart: unless-stopped
    env_file:
      - .env.appwrite
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - appwrite-builds:/storage/builds:rw
      - appwrite-functions:/storage/functions:rw
      - /tmp:/tmp:rw
    networks:
      - appwrite
      - runtimes
    logging: *default-logging

  openruntimes-proxy:
    container_name: openruntimes-proxy
    hostname: proxy
    image: openruntimes/proxy:0.5.5
    restart: unless-stopped
    env_file:
      - .env.appwrite
    depends_on:
      - openruntimes-executor
    networks:
      - appwrite
      - runtimes
    logging: *default-logging

  mariadb:
    container_name: appwrite-mariadb
    image: mariadb:10.11
    restart: unless-stopped
    env_file:
      - .env.appwrite
    environment:
      MARIADB_AUTO_UPGRADE: 1
    command: "mysqld --innodb-flush-method=fsync"
    networks:
      - appwrite
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    logging: *default-logging

  redis:
    container_name: appwrite-redis
    image: redis:7.2.4-alpine
    restart: unless-stopped
    command: >
      redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --maxmemory-samples 5
    networks:
      - appwrite
    volumes:
      - appwrite-redis:/data:rw
    ports:
      - "6379:6379"
    logging: *default-logging

  maildev:
    container_name: appwrite-maildev
    image: appwrite/mailcatcher:1.0.0
    restart: unless-stopped
    networks:
      - appwrite
    ports:
      - "9503:1080"
    logging: *default-logging

networks:
  gateway:
    name: gateway
  appwrite:
    name: appwrite
  runtimes:
    name: runtimes

volumes:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-certificates:
  appwrite-functions:
  appwrite-builds:
  appwrite-config:

